[INFO   ] Logger: Record log in /storage/emulated/0/Documents/project_utopia/.kivy/logs/kivy_21-11-12_15.txt
[INFO   ] Kivy: v2.0.0
[INFO   ] Kivy: Installed at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] Python: v3.9.7 (default, Oct  6 2021, 01:34:26) 
[GCC 11.1.0]
[INFO   ] Python: Interpreter at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3"
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/storage/emulated/0/Documents/project_utopia/utopia_app.py", line 3, in <module>
[WARNING] stderr:     
[WARNING] stderr: ModuleNotFoundError: No module named 'functool'
